//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyclone.LicenseManagement.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyclone.LicenseManagement.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Activation Days: 的本地化字符串。
        /// </summary>
        internal static string Activation_Days_ {
            get {
                return ResourceManager.GetString("Activation Days:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear License File 的本地化字符串。
        /// </summary>
        internal static string Clear_License_File {
            get {
                return ResourceManager.GetString("Clear License File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name: 的本地化字符串。
        /// </summary>
        internal static string Customer_Name_ {
            get {
                return ResourceManager.GetString("Customer Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email: 的本地化字符串。
        /// </summary>
        internal static string Email_ {
            get {
                return ResourceManager.GetString("Email:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expiration Date: 的本地化字符串。
        /// </summary>
        internal static string Expiration_Date_ {
            get {
                return ResourceManager.GetString("Expiration Date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Key 的本地化字符串。
        /// </summary>
        internal static string Generate_Key {
            get {
                return ResourceManager.GetString("Generate Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware 的本地化字符串。
        /// </summary>
        internal static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Count: 的本地化字符串。
        /// </summary>
        internal static string License_Count_ {
            get {
                return ResourceManager.GetString("License Count:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License File Management 的本地化字符串。
        /// </summary>
        internal static string License_File_Management {
            get {
                return ResourceManager.GetString("License File Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Type: 的本地化字符串。
        /// </summary>
        internal static string License_Type_ {
            get {
                return ResourceManager.GetString("License Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load License File 的本地化字符串。
        /// </summary>
        internal static string Load_License_File {
            get {
                return ResourceManager.GetString("Load License File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must generate key before saving license file... 的本地化字符串。
        /// </summary>
        internal static string Must_generate_key_before_saving_license_file___ {
            get {
                return ResourceManager.GetString("Must generate key before saving license file...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public Key: 的本地化字符串。
        /// </summary>
        internal static string Public_Key_ {
            get {
                return ResourceManager.GetString("Public Key:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regenerate 的本地化字符串。
        /// </summary>
        internal static string Regenerate {
            get {
                return ResourceManager.GetString("Regenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save License File 的本地化字符串。
        /// </summary>
        internal static string Save_License_File {
            get {
                return ResourceManager.GetString("Save License File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number: 的本地化字符串。
        /// </summary>
        internal static string Serial_Number_ {
            get {
                return ResourceManager.GetString("Serial Number:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature: 的本地化字符串。
        /// </summary>
        internal static string Signature_ {
            get {
                return ResourceManager.GetString("Signature:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trial 的本地化字符串。
        /// </summary>
        internal static string Trial {
            get {
                return ResourceManager.GetString("Trial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate License File 的本地化字符串。
        /// </summary>
        internal static string Validate_License_File {
            get {
                return ResourceManager.GetString("Validate License File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
